# Generated by Django 4.1.6 on 2023-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('vegOnly', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('Cost', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=1000)),
                ('cuisineTypes', models.CharField(choices=[('South Indian', 'South Indian'), ('Korean', 'Korean'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('French', 'French'), ('north indian', 'north indian')], max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('isOpen', models.BinaryField(choices=[(True, True), (False, False)], default=True)),
            ],
        ),
    ]
